seat=1

[CONTROLLER]
input_device="/dev/input/by-id/usb-ShanWan_Trust-GMP-04-event-joystick"

[MQTT]
broker_ip="10.3.141.1"

[CrazyComet]
magazine_size=5

[CrazyComet.turrets]
vertical_offset=0
horizontal_offset=0