site_name: Code References - Controller
site_url: https://4d-game.github.io/Controller

nav:
  - Home: https://4d-game.github.io
  - Coding Style: https://4d-game.github.io/coding-style/cpp/
  - Code References:
      Controller:
        - Setup: index.md
        - Game SDK:
            Structure: sdk/index.md
            Key Maps: sdk/key-maps.md
            Config File: sdk/config-file.md
            Code References:
              - Game: sdk/code-references/game.md
              - GameIO: sdk/code-references/game-io.md
      Gamecontrol: https://4d-game.github.io/Watcherstream/

repo_url: https://github.com/4D-Game/Controller
repo_name: 4D-Game/Controller

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # - scheme: default
    #   primary: light blue
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    - scheme: slate
      primary: light blue
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      watch:
        - lib/gamecontrol_sdk
        - src
  - mermaid2:
      arguments:
        theme: 'dark'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - attr_list
  - md_in_html
