site_name: Code References - Controller
site_url: https://4d-game.github.io/Streamer

nav:
  - Home: https://4d-game.github.io
  - Coding Style: https://4d-game.github.io/coding-style/cpp/
  - Code References:
      Streamer:
        - Setup: index.md
        - SDK: sdk/index.md
      Controller: https://4d-game.github.io/Controller/
      Watcherstream: https://4d-game.github.io/Watcherstream/

repo_url: https://github.com/4D-Game/Streamer
repo_name: 4D-Game/Streamer

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # - scheme: default
    #   primary: light blue
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    - scheme: slate
      primary: light blue
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      watch:
        - src
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'light'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - attr_list
  - md_in_html
